// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
using System;
using Bicep.Core;
using Bicep.Core.Resources;
using Bicep.Core.TypeSystem;
namespace Bicep.Resources.Types
{
    [ResourceTypeRegisterableAttribute]
    public class Microsoft_Sql_2017_10_01_preview
    {
        private const string ProviderNamespace = "Microsoft.Sql";
        private const string ApiVersion = "2017-10-01-preview";
        private static readonly ResourceTypeReference ResourceTypeReference_servers_databases = new ResourceTypeReference(ProviderNamespace, new[]{"servers", "databases"}, ApiVersion);
        private static readonly ResourceTypeReference ResourceTypeReference_servers_elasticPools = new ResourceTypeReference(ProviderNamespace, new[]{"servers", "elasticPools"}, ApiVersion);
        private static readonly ResourceTypeReference ResourceTypeReference_locations_instanceFailoverGroups = new ResourceTypeReference(ProviderNamespace, new[]{"locations", "instanceFailoverGroups"}, ApiVersion);
        private static readonly ResourceTypeReference ResourceTypeReference_managedInstances_keys = new ResourceTypeReference(ProviderNamespace, new[]{"managedInstances", "keys"}, ApiVersion);
        private static readonly ResourceTypeReference ResourceTypeReference_managedInstances_encryptionProtector = new ResourceTypeReference(ProviderNamespace, new[]{"managedInstances", "encryptionProtector"}, ApiVersion);
        private static readonly ResourceTypeReference ResourceTypeReference_managedInstances_databases_vulnerabilityAssessments = new ResourceTypeReference(ProviderNamespace, new[]{"managedInstances", "databases", "vulnerabilityAssessments"}, ApiVersion);
        private static readonly ResourceTypeReference ResourceTypeReference_managedInstances_databases_vulnerabilityAssessments_rules_baselines = new ResourceTypeReference(ProviderNamespace, new[]{"managedInstances", "databases", "vulnerabilityAssessments", "rules", "baselines"}, ApiVersion);
        private static Lazy<Microsoft_Sql_2017_10_01_preview> InstanceLazy = new Lazy<Microsoft_Sql_2017_10_01_preview>(() => new Microsoft_Sql_2017_10_01_preview());
        private Microsoft_Sql_2017_10_01_preview()
        {
            Sku = new NamedObjectType("Sku", new ITypeProperty[]{new TypeProperty("name", LanguageConstants.String, TypePropertyFlags.Required), new TypeProperty("tier", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("size", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("family", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("capacity", LanguageConstants.Int, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            DatabaseProperties = new NamedObjectType("DatabaseProperties", new ITypeProperty[]{new TypeProperty("createMode", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("collation", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("maxSizeBytes", LanguageConstants.Int, TypePropertyFlags.None), new TypeProperty("sampleName", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("elasticPoolId", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("sourceDatabaseId", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("restorePointInTime", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("sourceDatabaseDeletionDate", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("recoveryServicesRecoveryPointId", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("longTermRetentionBackupResourceId", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("recoverableDatabaseId", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("restorableDroppedDatabaseId", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("catalogCollation", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("zoneRedundant", LanguageConstants.Bool, TypePropertyFlags.None), new TypeProperty("licenseType", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("readScale", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("readReplicaCount", LanguageConstants.Int, TypePropertyFlags.None), new TypeProperty("autoPauseDelay", LanguageConstants.Int, TypePropertyFlags.None), new TypeProperty("minCapacity", LanguageConstants.Int, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            ElasticPoolProperties = new NamedObjectType("ElasticPoolProperties", new ITypeProperty[]{new TypeProperty("maxSizeBytes", LanguageConstants.Int, TypePropertyFlags.None), new LazyTypeProperty("perDatabaseSettings", () => ElasticPoolPerDatabaseSettings, TypePropertyFlags.None), new TypeProperty("zoneRedundant", LanguageConstants.Bool, TypePropertyFlags.None), new TypeProperty("licenseType", LanguageConstants.String, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            ElasticPoolPerDatabaseSettings = new NamedObjectType("ElasticPoolPerDatabaseSettings", new ITypeProperty[]{new TypeProperty("minCapacity", LanguageConstants.Int, TypePropertyFlags.None), new TypeProperty("maxCapacity", LanguageConstants.Int, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            DatabaseVulnerabilityAssessmentRuleBaselineProperties = new NamedObjectType("DatabaseVulnerabilityAssessmentRuleBaselineProperties", new ITypeProperty[]{new TypeProperty("baselineResults", LanguageConstants.Array, TypePropertyFlags.Required)}, null, TypePropertyFlags.None);
            DatabaseVulnerabilityAssessmentRuleBaselineItem = new NamedObjectType("DatabaseVulnerabilityAssessmentRuleBaselineItem", new ITypeProperty[]{new TypeProperty("result", LanguageConstants.Array, TypePropertyFlags.Required)}, null, TypePropertyFlags.None);
            DatabaseVulnerabilityAssessmentProperties = new NamedObjectType("DatabaseVulnerabilityAssessmentProperties", new ITypeProperty[]{new TypeProperty("storageContainerPath", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("storageContainerSasKey", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("storageAccountAccessKey", LanguageConstants.String, TypePropertyFlags.None), new LazyTypeProperty("recurringScans", () => VulnerabilityAssessmentRecurringScansProperties, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            VulnerabilityAssessmentRecurringScansProperties = new NamedObjectType("VulnerabilityAssessmentRecurringScansProperties", new ITypeProperty[]{new TypeProperty("isEnabled", LanguageConstants.Bool, TypePropertyFlags.None), new TypeProperty("emailSubscriptionAdmins", LanguageConstants.Bool, TypePropertyFlags.None), new TypeProperty("emails", LanguageConstants.Array, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            InstanceFailoverGroupProperties = new NamedObjectType("InstanceFailoverGroupProperties", new ITypeProperty[]{new LazyTypeProperty("readWriteEndpoint", () => InstanceFailoverGroupReadWriteEndpoint, TypePropertyFlags.Required), new LazyTypeProperty("readOnlyEndpoint", () => InstanceFailoverGroupReadOnlyEndpoint, TypePropertyFlags.None), new TypeProperty("partnerRegions", LanguageConstants.Array, TypePropertyFlags.Required), new TypeProperty("managedInstancePairs", LanguageConstants.Array, TypePropertyFlags.Required)}, null, TypePropertyFlags.None);
            InstanceFailoverGroupReadWriteEndpoint = new NamedObjectType("InstanceFailoverGroupReadWriteEndpoint", new ITypeProperty[]{new TypeProperty("failoverPolicy", LanguageConstants.String, TypePropertyFlags.Required), new TypeProperty("failoverWithDataLossGracePeriodMinutes", LanguageConstants.Int, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            InstanceFailoverGroupReadOnlyEndpoint = new NamedObjectType("InstanceFailoverGroupReadOnlyEndpoint", new ITypeProperty[]{new TypeProperty("failoverPolicy", LanguageConstants.String, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            PartnerRegionInfo = new NamedObjectType("PartnerRegionInfo", new ITypeProperty[]{new TypeProperty("location", LanguageConstants.String, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            ManagedInstancePairInfo = new NamedObjectType("ManagedInstancePairInfo", new ITypeProperty[]{new TypeProperty("primaryManagedInstanceId", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("partnerManagedInstanceId", LanguageConstants.String, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            ManagedInstanceKeyProperties = new NamedObjectType("ManagedInstanceKeyProperties", new ITypeProperty[]{new TypeProperty("serverKeyType", LanguageConstants.String, TypePropertyFlags.Required), new TypeProperty("uri", LanguageConstants.String, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            ManagedInstanceEncryptionProtectorProperties = new NamedObjectType("ManagedInstanceEncryptionProtectorProperties", new ITypeProperty[]{new TypeProperty("serverKeyName", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("serverKeyType", LanguageConstants.String, TypePropertyFlags.Required)}, null, TypePropertyFlags.None);
            ResourceType_servers_databases = new ResourceType("Microsoft.Sql/servers/databases", new ITypeProperty[]{new TypeProperty("location", LanguageConstants.String, TypePropertyFlags.Required), new TypeProperty("tags", LanguageConstants.Any, TypePropertyFlags.None), new LazyTypeProperty("sku", () => Sku, TypePropertyFlags.None), new LazyTypeProperty("properties", () => DatabaseProperties, TypePropertyFlags.Required), new TypeProperty("name", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.Required), new TypeProperty("type", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.ReadOnly), new TypeProperty("apiVersion", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.ReadOnly)}, null, ResourceTypeReference_servers_databases);
            ResourceType_servers_elasticPools = new ResourceType("Microsoft.Sql/servers/elasticPools", new ITypeProperty[]{new TypeProperty("location", LanguageConstants.String, TypePropertyFlags.Required), new TypeProperty("tags", LanguageConstants.Any, TypePropertyFlags.None), new LazyTypeProperty("sku", () => Sku, TypePropertyFlags.None), new LazyTypeProperty("properties", () => ElasticPoolProperties, TypePropertyFlags.Required), new TypeProperty("name", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.Required), new TypeProperty("type", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.ReadOnly), new TypeProperty("apiVersion", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.ReadOnly)}, null, ResourceTypeReference_servers_elasticPools);
            ResourceType_locations_instanceFailoverGroups = new ResourceType("Microsoft.Sql/locations/instanceFailoverGroups", new ITypeProperty[]{new LazyTypeProperty("properties", () => InstanceFailoverGroupProperties, TypePropertyFlags.Required), new TypeProperty("name", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.Required), new TypeProperty("type", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.ReadOnly), new TypeProperty("apiVersion", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.ReadOnly)}, null, ResourceTypeReference_locations_instanceFailoverGroups);
            ResourceType_managedInstances_keys = new ResourceType("Microsoft.Sql/managedInstances/keys", new ITypeProperty[]{new LazyTypeProperty("properties", () => ManagedInstanceKeyProperties, TypePropertyFlags.Required), new TypeProperty("name", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.Required), new TypeProperty("type", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.ReadOnly), new TypeProperty("apiVersion", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.ReadOnly)}, null, ResourceTypeReference_managedInstances_keys);
            ResourceType_managedInstances_encryptionProtector = new ResourceType("Microsoft.Sql/managedInstances/encryptionProtector", new ITypeProperty[]{new LazyTypeProperty("properties", () => ManagedInstanceEncryptionProtectorProperties, TypePropertyFlags.Required), new TypeProperty("name", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.Required), new TypeProperty("type", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.ReadOnly), new TypeProperty("apiVersion", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.ReadOnly)}, null, ResourceTypeReference_managedInstances_encryptionProtector);
            ResourceType_managedInstances_databases_vulnerabilityAssessments = new ResourceType("Microsoft.Sql/managedInstances/databases/vulnerabilityAssessments", new ITypeProperty[]{new LazyTypeProperty("properties", () => DatabaseVulnerabilityAssessmentProperties, TypePropertyFlags.Required), new TypeProperty("name", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.Required), new TypeProperty("type", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.ReadOnly), new TypeProperty("apiVersion", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.ReadOnly)}, null, ResourceTypeReference_managedInstances_databases_vulnerabilityAssessments);
            ResourceType_managedInstances_databases_vulnerabilityAssessments_rules_baselines = new ResourceType("Microsoft.Sql/managedInstances/databases/vulnerabilityAssessments/rules/baselines", new ITypeProperty[]{new LazyTypeProperty("properties", () => DatabaseVulnerabilityAssessmentRuleBaselineProperties, TypePropertyFlags.Required), new TypeProperty("name", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.Required), new TypeProperty("type", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.ReadOnly), new TypeProperty("apiVersion", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.ReadOnly)}, null, ResourceTypeReference_managedInstances_databases_vulnerabilityAssessments_rules_baselines);
        }
        public static void Register(IResourceTypeRegistrar registrar)
        {
            registrar.RegisterType(ResourceTypeReference_servers_databases, () => InstanceLazy.Value.ResourceType_servers_databases);
            registrar.RegisterType(ResourceTypeReference_servers_elasticPools, () => InstanceLazy.Value.ResourceType_servers_elasticPools);
            registrar.RegisterType(ResourceTypeReference_locations_instanceFailoverGroups, () => InstanceLazy.Value.ResourceType_locations_instanceFailoverGroups);
            registrar.RegisterType(ResourceTypeReference_managedInstances_keys, () => InstanceLazy.Value.ResourceType_managedInstances_keys);
            registrar.RegisterType(ResourceTypeReference_managedInstances_encryptionProtector, () => InstanceLazy.Value.ResourceType_managedInstances_encryptionProtector);
            registrar.RegisterType(ResourceTypeReference_managedInstances_databases_vulnerabilityAssessments, () => InstanceLazy.Value.ResourceType_managedInstances_databases_vulnerabilityAssessments);
            registrar.RegisterType(ResourceTypeReference_managedInstances_databases_vulnerabilityAssessments_rules_baselines, () => InstanceLazy.Value.ResourceType_managedInstances_databases_vulnerabilityAssessments_rules_baselines);
        }
        private readonly ResourceType ResourceType_servers_databases;
        private readonly ResourceType ResourceType_servers_elasticPools;
        private readonly ResourceType ResourceType_locations_instanceFailoverGroups;
        private readonly ResourceType ResourceType_managedInstances_keys;
        private readonly ResourceType ResourceType_managedInstances_encryptionProtector;
        private readonly ResourceType ResourceType_managedInstances_databases_vulnerabilityAssessments;
        private readonly ResourceType ResourceType_managedInstances_databases_vulnerabilityAssessments_rules_baselines;
        private readonly TypeSymbol Sku;
        private readonly TypeSymbol DatabaseProperties;
        private readonly TypeSymbol ElasticPoolProperties;
        private readonly TypeSymbol ElasticPoolPerDatabaseSettings;
        private readonly TypeSymbol DatabaseVulnerabilityAssessmentRuleBaselineProperties;
        private readonly TypeSymbol DatabaseVulnerabilityAssessmentRuleBaselineItem;
        private readonly TypeSymbol DatabaseVulnerabilityAssessmentProperties;
        private readonly TypeSymbol VulnerabilityAssessmentRecurringScansProperties;
        private readonly TypeSymbol InstanceFailoverGroupProperties;
        private readonly TypeSymbol InstanceFailoverGroupReadWriteEndpoint;
        private readonly TypeSymbol InstanceFailoverGroupReadOnlyEndpoint;
        private readonly TypeSymbol PartnerRegionInfo;
        private readonly TypeSymbol ManagedInstancePairInfo;
        private readonly TypeSymbol ManagedInstanceKeyProperties;
        private readonly TypeSymbol ManagedInstanceEncryptionProtectorProperties;
    }
}
