// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
using System;
using Bicep.Core;
using Bicep.Core.Resources;
using Bicep.Core.TypeSystem;
namespace Bicep.Resources.Types
{
    [ResourceTypeRegisterableAttribute]
    public class Microsoft_Sql_2020_02_02_preview
    {
        private const string ProviderNamespace = "Microsoft.Sql";
        private const string ApiVersion = "2020-02-02-preview";
        private static readonly ResourceTypeReference ResourceTypeReference_managedInstances = new ResourceTypeReference(ProviderNamespace, new[]{"managedInstances"}, ApiVersion);
        private static readonly ResourceTypeReference ResourceTypeReference_managedInstances_databases = new ResourceTypeReference(ProviderNamespace, new[]{"managedInstances", "databases"}, ApiVersion);
        private static readonly ResourceTypeReference ResourceTypeReference_servers_azureADOnlyAuthentications = new ResourceTypeReference(ProviderNamespace, new[]{"servers", "azureADOnlyAuthentications"}, ApiVersion);
        private static readonly ResourceTypeReference ResourceTypeReference_servers_databases_backupShortTermRetentionPolicies = new ResourceTypeReference(ProviderNamespace, new[]{"servers", "databases", "backupShortTermRetentionPolicies"}, ApiVersion);
        private static Lazy<Microsoft_Sql_2020_02_02_preview> InstanceLazy = new Lazy<Microsoft_Sql_2020_02_02_preview>(() => new Microsoft_Sql_2020_02_02_preview());
        private Microsoft_Sql_2020_02_02_preview()
        {
            ResourceIdentity = new NamedObjectType("ResourceIdentity", new ITypeProperty[]{new TypeProperty("type", LanguageConstants.String, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            Sku = new NamedObjectType("Sku", new ITypeProperty[]{new TypeProperty("name", LanguageConstants.String, TypePropertyFlags.Required), new TypeProperty("tier", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("size", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("family", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("capacity", LanguageConstants.Int, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            ManagedInstanceProperties = new NamedObjectType("ManagedInstanceProperties", new ITypeProperty[]{new TypeProperty("managedInstanceCreateMode", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("administratorLogin", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("administratorLoginPassword", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("subnetId", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("licenseType", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("vCores", LanguageConstants.Int, TypePropertyFlags.None), new TypeProperty("storageSizeInGB", LanguageConstants.Int, TypePropertyFlags.None), new TypeProperty("collation", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("dnsZonePartner", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("publicDataEndpointEnabled", LanguageConstants.Bool, TypePropertyFlags.None), new TypeProperty("sourceManagedInstanceId", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("restorePointInTime", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("proxyOverride", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("timezoneId", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("instancePoolId", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("maintenanceConfigurationId", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("minimalTlsVersion", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("storageAccountType", LanguageConstants.String, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            BackupShortTermRetentionPolicyProperties = new NamedObjectType("BackupShortTermRetentionPolicyProperties", new ITypeProperty[]{new TypeProperty("retentionDays", LanguageConstants.Int, TypePropertyFlags.None), new TypeProperty("diffBackupIntervalInHours", LanguageConstants.Int, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            ManagedDatabaseProperties = new NamedObjectType("ManagedDatabaseProperties", new ITypeProperty[]{new TypeProperty("collation", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("restorePointInTime", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("catalogCollation", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("createMode", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("storageContainerUri", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("sourceDatabaseId", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("restorableDroppedDatabaseId", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("storageContainerSasToken", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("recoverableDatabaseId", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("longTermRetentionBackupResourceId", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("autoCompleteRestore", LanguageConstants.Bool, TypePropertyFlags.None), new TypeProperty("lastBackupName", LanguageConstants.String, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            AzureADOnlyAuthProperties = new NamedObjectType("AzureADOnlyAuthProperties", new ITypeProperty[]{new TypeProperty("azureADOnlyAuthentication", LanguageConstants.Bool, TypePropertyFlags.Required)}, null, TypePropertyFlags.None);
            ResourceType_managedInstances = new ResourceType("Microsoft.Sql/managedInstances", new ITypeProperty[]{new TypeProperty("location", LanguageConstants.String, TypePropertyFlags.Required), new TypeProperty("tags", LanguageConstants.Any, TypePropertyFlags.None), new LazyTypeProperty("identity", () => ResourceIdentity, TypePropertyFlags.None), new LazyTypeProperty("sku", () => Sku, TypePropertyFlags.None), new LazyTypeProperty("properties", () => ManagedInstanceProperties, TypePropertyFlags.Required), new TypeProperty("name", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.Required), new TypeProperty("type", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.ReadOnly), new TypeProperty("apiVersion", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.ReadOnly)}, null, ResourceTypeReference_managedInstances);
            ResourceType_managedInstances_databases = new ResourceType("Microsoft.Sql/managedInstances/databases", new ITypeProperty[]{new TypeProperty("location", LanguageConstants.String, TypePropertyFlags.Required), new TypeProperty("tags", LanguageConstants.Any, TypePropertyFlags.None), new LazyTypeProperty("properties", () => ManagedDatabaseProperties, TypePropertyFlags.Required), new TypeProperty("name", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.Required), new TypeProperty("type", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.ReadOnly), new TypeProperty("apiVersion", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.ReadOnly)}, null, ResourceTypeReference_managedInstances_databases);
            ResourceType_servers_azureADOnlyAuthentications = new ResourceType("Microsoft.Sql/servers/azureADOnlyAuthentications", new ITypeProperty[]{new LazyTypeProperty("properties", () => AzureADOnlyAuthProperties, TypePropertyFlags.Required), new TypeProperty("name", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.Required), new TypeProperty("type", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.ReadOnly), new TypeProperty("apiVersion", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.ReadOnly)}, null, ResourceTypeReference_servers_azureADOnlyAuthentications);
            ResourceType_servers_databases_backupShortTermRetentionPolicies = new ResourceType("Microsoft.Sql/servers/databases/backupShortTermRetentionPolicies", new ITypeProperty[]{new LazyTypeProperty("properties", () => BackupShortTermRetentionPolicyProperties, TypePropertyFlags.Required), new TypeProperty("name", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.Required), new TypeProperty("type", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.ReadOnly), new TypeProperty("apiVersion", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.ReadOnly)}, null, ResourceTypeReference_servers_databases_backupShortTermRetentionPolicies);
        }
        public static void Register(IResourceTypeRegistrar registrar)
        {
            registrar.RegisterType(ResourceTypeReference_managedInstances, () => InstanceLazy.Value.ResourceType_managedInstances);
            registrar.RegisterType(ResourceTypeReference_managedInstances_databases, () => InstanceLazy.Value.ResourceType_managedInstances_databases);
            registrar.RegisterType(ResourceTypeReference_servers_azureADOnlyAuthentications, () => InstanceLazy.Value.ResourceType_servers_azureADOnlyAuthentications);
            registrar.RegisterType(ResourceTypeReference_servers_databases_backupShortTermRetentionPolicies, () => InstanceLazy.Value.ResourceType_servers_databases_backupShortTermRetentionPolicies);
        }
        private readonly ResourceType ResourceType_managedInstances;
        private readonly ResourceType ResourceType_managedInstances_databases;
        private readonly ResourceType ResourceType_servers_azureADOnlyAuthentications;
        private readonly ResourceType ResourceType_servers_databases_backupShortTermRetentionPolicies;
        private readonly TypeSymbol ResourceIdentity;
        private readonly TypeSymbol Sku;
        private readonly TypeSymbol ManagedInstanceProperties;
        private readonly TypeSymbol BackupShortTermRetentionPolicyProperties;
        private readonly TypeSymbol ManagedDatabaseProperties;
        private readonly TypeSymbol AzureADOnlyAuthProperties;
    }
}
