// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
using System;
using Bicep.Core;
using Bicep.Core.Resources;
using Bicep.Core.TypeSystem;
namespace Bicep.Resources.Types
{
    [ResourceTypeRegisterableAttribute]
    public class Microsoft_ServiceFabric_2020_01_01_preview
    {
        private const string ProviderNamespace = "Microsoft.ServiceFabric";
        private const string ApiVersion = "2020-01-01-preview";
        private static readonly ResourceTypeReference ResourceTypeReference_managedClusters = new ResourceTypeReference(ProviderNamespace, new[]{"managedClusters"}, ApiVersion);
        private static readonly ResourceTypeReference ResourceTypeReference_managedClusters_nodeTypes = new ResourceTypeReference(ProviderNamespace, new[]{"managedClusters", "nodeTypes"}, ApiVersion);
        private static Lazy<Microsoft_ServiceFabric_2020_01_01_preview> InstanceLazy = new Lazy<Microsoft_ServiceFabric_2020_01_01_preview>(() => new Microsoft_ServiceFabric_2020_01_01_preview());
        private Microsoft_ServiceFabric_2020_01_01_preview()
        {
            ManagedClusterProperties = new NamedObjectType("ManagedClusterProperties", new ITypeProperty[]{new TypeProperty("dnsName", LanguageConstants.String, TypePropertyFlags.Required), new TypeProperty("clientConnectionPort", LanguageConstants.Int, TypePropertyFlags.None), new TypeProperty("httpGatewayConnectionPort", LanguageConstants.Int, TypePropertyFlags.None), new TypeProperty("adminUserName", LanguageConstants.String, TypePropertyFlags.Required), new TypeProperty("adminPassword", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("loadBalancingRules", LanguageConstants.Array, TypePropertyFlags.None), new TypeProperty("clients", LanguageConstants.Array, TypePropertyFlags.None), new LazyTypeProperty("azureActiveDirectory", () => AzureActiveDirectory, TypePropertyFlags.None), new TypeProperty("fabricSettings", LanguageConstants.Array, TypePropertyFlags.None), new TypeProperty("useTestExtension", LanguageConstants.Bool, TypePropertyFlags.None), new TypeProperty("clusterCodeVersion", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("clusterUpgradeMode", LanguageConstants.String, TypePropertyFlags.None), new LazyTypeProperty("clusterUpgradeDescription", () => ClusterUpgradePolicy, TypePropertyFlags.None), new TypeProperty("reverseProxyEndpointPort", LanguageConstants.Int, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            LoadBalancingRule = new NamedObjectType("LoadBalancingRule", new ITypeProperty[]{new TypeProperty("frontendPort", LanguageConstants.Int, TypePropertyFlags.Required), new TypeProperty("backendPort", LanguageConstants.Int, TypePropertyFlags.Required), new TypeProperty("protocol", LanguageConstants.String, TypePropertyFlags.Required), new TypeProperty("probeProtocol", LanguageConstants.String, TypePropertyFlags.Required), new TypeProperty("probeRequestPath", LanguageConstants.String, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            ClientCertificate = new NamedObjectType("ClientCertificate", new ITypeProperty[]{new TypeProperty("isAdmin", LanguageConstants.Bool, TypePropertyFlags.Required), new TypeProperty("thumbprint", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("commonName", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("issuerThumbprint", LanguageConstants.String, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            AzureActiveDirectory = new NamedObjectType("AzureActiveDirectory", new ITypeProperty[]{new TypeProperty("tenantId", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("clusterApplication", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("clientApplication", LanguageConstants.String, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            SettingsSectionDescription = new NamedObjectType("SettingsSectionDescription", new ITypeProperty[]{new TypeProperty("name", LanguageConstants.String, TypePropertyFlags.Required), new TypeProperty("parameters", LanguageConstants.Array, TypePropertyFlags.Required)}, null, TypePropertyFlags.None);
            SettingsParameterDescription = new NamedObjectType("SettingsParameterDescription", new ITypeProperty[]{new TypeProperty("name", LanguageConstants.String, TypePropertyFlags.Required), new TypeProperty("value", LanguageConstants.String, TypePropertyFlags.Required)}, null, TypePropertyFlags.None);
            ClusterUpgradePolicy = new NamedObjectType("ClusterUpgradePolicy", new ITypeProperty[]{new TypeProperty("forceRestart", LanguageConstants.Bool, TypePropertyFlags.None), new TypeProperty("upgradeReplicaSetCheckTimeout", LanguageConstants.String, TypePropertyFlags.Required), new TypeProperty("healthCheckWaitDuration", LanguageConstants.String, TypePropertyFlags.Required), new TypeProperty("healthCheckStableDuration", LanguageConstants.String, TypePropertyFlags.Required), new TypeProperty("healthCheckRetryTimeout", LanguageConstants.String, TypePropertyFlags.Required), new TypeProperty("upgradeTimeout", LanguageConstants.String, TypePropertyFlags.Required), new TypeProperty("upgradeDomainTimeout", LanguageConstants.String, TypePropertyFlags.Required), new LazyTypeProperty("healthPolicy", () => ClusterHealthPolicy, TypePropertyFlags.Required), new LazyTypeProperty("deltaHealthPolicy", () => ClusterUpgradeDeltaHealthPolicy, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            ClusterHealthPolicy = new NamedObjectType("ClusterHealthPolicy", new ITypeProperty[]{new TypeProperty("maxPercentUnhealthyNodes", LanguageConstants.Int, TypePropertyFlags.None), new TypeProperty("maxPercentUnhealthyApplications", LanguageConstants.Int, TypePropertyFlags.None), new TypeProperty("applicationHealthPolicies", LanguageConstants.Any, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            ApplicationHealthPolicy = new NamedObjectType("ApplicationHealthPolicy", new ITypeProperty[]{new LazyTypeProperty("defaultServiceTypeHealthPolicy", () => ServiceTypeHealthPolicy, TypePropertyFlags.None), new TypeProperty("serviceTypeHealthPolicies", LanguageConstants.Any, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            ServiceTypeHealthPolicy = new NamedObjectType("ServiceTypeHealthPolicy", new ITypeProperty[]{new TypeProperty("maxPercentUnhealthyServices", LanguageConstants.Int, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            ClusterUpgradeDeltaHealthPolicy = new NamedObjectType("ClusterUpgradeDeltaHealthPolicy", new ITypeProperty[]{new TypeProperty("maxPercentDeltaUnhealthyNodes", LanguageConstants.Int, TypePropertyFlags.Required), new TypeProperty("maxPercentUpgradeDomainDeltaUnhealthyNodes", LanguageConstants.Int, TypePropertyFlags.Required), new TypeProperty("maxPercentDeltaUnhealthyApplications", LanguageConstants.Int, TypePropertyFlags.Required), new TypeProperty("applicationDeltaHealthPolicies", LanguageConstants.Any, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            ApplicationDeltaHealthPolicy = new NamedObjectType("ApplicationDeltaHealthPolicy", new ITypeProperty[]{new LazyTypeProperty("defaultServiceTypeDeltaHealthPolicy", () => ServiceTypeDeltaHealthPolicy, TypePropertyFlags.None), new TypeProperty("serviceTypeDeltaHealthPolicies", LanguageConstants.Any, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            ServiceTypeDeltaHealthPolicy = new NamedObjectType("ServiceTypeDeltaHealthPolicy", new ITypeProperty[]{new TypeProperty("maxPercentDeltaUnhealthyServices", LanguageConstants.Int, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            Sku = new NamedObjectType("Sku", new ITypeProperty[]{new TypeProperty("name", LanguageConstants.String, TypePropertyFlags.Required)}, null, TypePropertyFlags.None);
            NodeTypeProperties = new NamedObjectType("NodeTypeProperties", new ITypeProperty[]{new TypeProperty("isPrimary", LanguageConstants.Bool, TypePropertyFlags.Required), new TypeProperty("vmInstanceCount", LanguageConstants.Int, TypePropertyFlags.Required), new TypeProperty("dataDiskSizeGB", LanguageConstants.Int, TypePropertyFlags.Required), new TypeProperty("placementProperties", LanguageConstants.Any, TypePropertyFlags.None), new TypeProperty("capacities", LanguageConstants.Any, TypePropertyFlags.None), new LazyTypeProperty("applicationPorts", () => EndpointRangeDescription, TypePropertyFlags.None), new LazyTypeProperty("ephemeralPorts", () => EndpointRangeDescription, TypePropertyFlags.None), new TypeProperty("vmSize", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("vmImagePublisher", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("vmImageOffer", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("vmImageSku", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("vmImageVersion", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("vmSecrets", LanguageConstants.Array, TypePropertyFlags.None), new TypeProperty("vmExtensions", LanguageConstants.Array, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            EndpointRangeDescription = new NamedObjectType("EndpointRangeDescription", new ITypeProperty[]{new TypeProperty("startPort", LanguageConstants.Int, TypePropertyFlags.Required), new TypeProperty("endPort", LanguageConstants.Int, TypePropertyFlags.Required)}, null, TypePropertyFlags.None);
            VaultSecretGroup = new NamedObjectType("VaultSecretGroup", new ITypeProperty[]{new LazyTypeProperty("sourceVault", () => SubResource, TypePropertyFlags.Required), new TypeProperty("vaultCertificates", LanguageConstants.Array, TypePropertyFlags.Required)}, null, TypePropertyFlags.None);
            SubResource = new NamedObjectType("SubResource", new ITypeProperty[]{new TypeProperty("id", LanguageConstants.String, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            VaultCertificate = new NamedObjectType("VaultCertificate", new ITypeProperty[]{new TypeProperty("certificateUrl", LanguageConstants.String, TypePropertyFlags.Required), new TypeProperty("certificateStore", LanguageConstants.String, TypePropertyFlags.Required)}, null, TypePropertyFlags.None);
            VMSSExtension = new NamedObjectType("VMSSExtension", new ITypeProperty[]{new TypeProperty("name", LanguageConstants.String, TypePropertyFlags.Required), new LazyTypeProperty("properties", () => VMSSExtensionProperties, TypePropertyFlags.Required)}, null, TypePropertyFlags.None);
            VMSSExtensionProperties = new NamedObjectType("VMSSExtensionProperties", new ITypeProperty[]{new TypeProperty("forceUpdateTag", LanguageConstants.String, TypePropertyFlags.None), new TypeProperty("publisher", LanguageConstants.String, TypePropertyFlags.Required), new TypeProperty("type", LanguageConstants.String, TypePropertyFlags.Required), new TypeProperty("typeHandlerVersion", LanguageConstants.String, TypePropertyFlags.Required), new TypeProperty("autoUpgradeMinorVersion", LanguageConstants.Bool, TypePropertyFlags.None), new TypeProperty("settings", LanguageConstants.Any, TypePropertyFlags.None), new TypeProperty("protectedSettings", LanguageConstants.Any, TypePropertyFlags.None), new TypeProperty("provisionAfterExtensions", LanguageConstants.Array, TypePropertyFlags.None)}, null, TypePropertyFlags.None);
            ResourceType_managedClusters = new ResourceType("Microsoft.ServiceFabric/managedClusters", new ITypeProperty[]{new TypeProperty("location", LanguageConstants.String, TypePropertyFlags.Required), new TypeProperty("tags", LanguageConstants.Any, TypePropertyFlags.None), new LazyTypeProperty("properties", () => ManagedClusterProperties, TypePropertyFlags.Required), new LazyTypeProperty("sku", () => Sku, TypePropertyFlags.None), new TypeProperty("name", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.Required), new TypeProperty("type", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.ReadOnly), new TypeProperty("apiVersion", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.ReadOnly)}, null, ResourceTypeReference_managedClusters);
            ResourceType_managedClusters_nodeTypes = new ResourceType("Microsoft.ServiceFabric/managedClusters/nodeTypes", new ITypeProperty[]{new TypeProperty("tags", LanguageConstants.Any, TypePropertyFlags.None), new LazyTypeProperty("properties", () => NodeTypeProperties, TypePropertyFlags.Required), new TypeProperty("name", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.Required), new TypeProperty("type", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.ReadOnly), new TypeProperty("apiVersion", LanguageConstants.String, TypePropertyFlags.SkipInlining | TypePropertyFlags.ReadOnly)}, null, ResourceTypeReference_managedClusters_nodeTypes);
        }
        public static void Register(IResourceTypeRegistrar registrar)
        {
            registrar.RegisterType(ResourceTypeReference_managedClusters, () => InstanceLazy.Value.ResourceType_managedClusters);
            registrar.RegisterType(ResourceTypeReference_managedClusters_nodeTypes, () => InstanceLazy.Value.ResourceType_managedClusters_nodeTypes);
        }
        private readonly ResourceType ResourceType_managedClusters;
        private readonly ResourceType ResourceType_managedClusters_nodeTypes;
        private readonly TypeSymbol ManagedClusterProperties;
        private readonly TypeSymbol LoadBalancingRule;
        private readonly TypeSymbol ClientCertificate;
        private readonly TypeSymbol AzureActiveDirectory;
        private readonly TypeSymbol SettingsSectionDescription;
        private readonly TypeSymbol SettingsParameterDescription;
        private readonly TypeSymbol ClusterUpgradePolicy;
        private readonly TypeSymbol ClusterHealthPolicy;
        private readonly TypeSymbol ApplicationHealthPolicy;
        private readonly TypeSymbol ServiceTypeHealthPolicy;
        private readonly TypeSymbol ClusterUpgradeDeltaHealthPolicy;
        private readonly TypeSymbol ApplicationDeltaHealthPolicy;
        private readonly TypeSymbol ServiceTypeDeltaHealthPolicy;
        private readonly TypeSymbol Sku;
        private readonly TypeSymbol NodeTypeProperties;
        private readonly TypeSymbol EndpointRangeDescription;
        private readonly TypeSymbol VaultSecretGroup;
        private readonly TypeSymbol SubResource;
        private readonly TypeSymbol VaultCertificate;
        private readonly TypeSymbol VMSSExtension;
        private readonly TypeSymbol VMSSExtensionProperties;
    }
}
